binde = $mainMod, RETURN, exec, $terminal 
bind = $mainMod, SPACE, exec, $menu

bind = $modCtrl, S, exec, hyprshot -m region -z -o ~/Pictures/Screenshots/
bind = $modCtrl ALT, S, exec, hyprshot -m window -z -o ~/Pictures/Screenshots/
bind = $modCtrl, A, exec, hyprshot -m output -z -o ~/Pictures/Screenshots/

bind = $modCtrl, Z, exec, $terminal sudo /opt/zapret/install_easy.sh
bind = $modCtrl+ALT, Z, exec, $terminal sudo /opt/zapret/uninstall_easy.sh

bind = $modCtrl, B, exec, killall waybar || hyprctl dispatch -- exec waybar -c ~/.config/waybar/Hyprland/config.jsonc -s ~/.config/waybar/Hyprland/style.css
