bind = $windowResize, V, togglesplit 

bind = $windowResize, F, fullscreen
binde = $windowResize, SPACE, togglefloating

binde = $mainMod, left, movefocus, l 
binde = $mainMod, right, movefocus, r
binde = $mainMod, up, movefocus, u
binde = $mainMod, down, movefocus, d

binde = $mainMod, H, movefocus, l
binde = $mainMod, L, movefocus, r
binde = $mainMod, K, movefocus, u
binde = $mainMod, J, movefocus, d

bind = $mainMod ALT, H, movewindoworgroup, l
bind = $mainMod ALT, L, movewindoworgroup, r
bind = $mainMod ALT, K, movewindoworgroup, u
bind = $mainMod ALT, J, movewindoworgroup, d 

binde = $windowResize, H, resizeactive, -100 0
binde = $windowResize, L, resizeactive, 100 0
binde = $windowResize, K, resizeactive, 0 -100
binde = $windowResize, J, resizeactive, 0 100 

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Group control
bind = $mainMod+SHIFT, TAB, togglegroup
bind = ALT, TAB, changegroupactive, f
bind = ALT+SHIFT, TAB, changegroupactive, b

