bind = $mainMod, $System, workspace, $System
bind = $mainMod, $Files, workspace, $Files
bind = $mainMod, $Chats, workspace, $Chats
bind = $mainMod, $Games, workspace, $Games
bind = $mainMod, $Virt, workspace, $Virt
bind = $mainMod, $Web, workspace, $Web
bind = $mainMod, $Dev, workspace, $Dev
bind = $mainMod, $Term, workspace, $Term

bind = $mainMod, S, workspace, $System 
bind = $mainMod, F, workspace, $Files 
bind = $mainMod, C, workspace, $Chats 
bind = $mainMod, G, workspace, $Games 
bind = $mainMod, V, workspace, $Virt 
bind = $mainMod, W, workspace, $Web 
bind = $mainMod, D, workspace, $Dev 
bind = $mainMod, T, workspace, $Term 

bind = $windowMove, $System, movetoworkspace, $System
bind = $windowMove, $Files, movetoworkspace, $Files 
bind = $windowMove, $Chats, movetoworkspace, $Chats 
bind = $windowMove, $Games, movetoworkspace, $Games 
bind = $windowMove, $Virt, movetoworkspace, $Virt 
bind = $windowMove, $Web, movetoworkspace, $Web 
bind = $windowMove, $Dev, movetoworkspace, $Dev 
bind = $windowMove, $Term, movetoworkspace, $Term 

bind = $windowMove, S, movetoworkspace, $System 
bind = $windowMove, F, movetoworkspace, $Files  
bind = $windowMove, C, movetoworkspace, $Chats  
bind = $windowMove, G, movetoworkspace, $Games  
bind = $windowMove, V, movetoworkspace, $Virt  
bind = $windowMove, W, movetoworkspace, $Web  
bind = $windowMove, D, movetoworkspace, $Dev  
bind = $windowMove, T, movetoworkspace, $Term  

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
binds:scroll_event_delay = 75

binde = $mainMod, N, workspace, m+1
binde = $mainMod, P, workspace, m-1

binde = $mainMod, TAB, workspace, prev

binde = $windowMove, N, movetoworkspace, m+1
binde = $windowMove, P, movetoworkspace, m-1

