decoration {
    rounding = 15
    rounding_power = 4.0

    active_opacity = 1.0
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0

    dim_inactive = true
    dim_around = 0.2
    dim_special = 0.2
    dim_strength = 0.1


    shadow {

        enabled = true
        range = 10
        render_power = 3
        color = rgba(000012aa)

    }

    blur {

        enabled = true
        size = 5
        passes = 1
        ignore_opacity = false 
        noise = 0.0
        contrast = 1.5
        vibrancy = 0.0

        new_optimizations = true
        xray = true
    }

    layerrule = blur, waybar
}

