group {
    col.border_inactive = rgba(542d8980)
    col.border_active = rgba(72359caa) rgba(72359cff) rgba(daaa56aa) rgba(daaa56ff) rgba(daaa5688) rgba(5f2881ff) rgba(5f288188) rgba(5f288175) 69deg

    groupbar {
        font_size = 14
        gradients = false
        stacked = false
        col.active = rgba(72359c90)
        col.inactive = rgba(542d8980)
        rounding = 100
        round_only_edges = false
        gaps_in = 1
        gaps_out = 2
    }
}
