misc {
    force_default_wallpaper = 1 
    disable_hyprland_logo = false 
    font_family = JetBrainsMono Nerd Font Mono
    enable_swallow = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = false
    new_window_takes_over_fullscreen = 2
}
