exec-once = nm-applet &
exec-once = sleep 2.0 && blueman-applet &
exec-once = kdeconnect-indicator &

# exec-once = wal -R &
exec-once = mako
exec-once = waybar -c ~/.config/waybar/Hyprland/config.jsonc -s ~/.config/waybar/Hyprland/style.css & hyprpaper &
exec-once = systemctl --user start hyprpolkitagent &
exec-once = ~/config/hypr/xdg-portal-hyprland
exec-once = systemctl --user start hyprpolkitagent &
exec-once = ollama serve &


exec-once = printf "[D-BUS Service]\nName=org.kde.kded6\nExec=/bin/false" > $HOME/.local/share/dbus-1/services/org.kde.kded6.service
exec-shutdown = rm $HOME/.local/share/dbus-1/services/org.kde.kded6.service

# Renaming workspaces
