source = ~/.config/hypr/workspaces/*.conf

exec-once = nm-applet
exec-once = blueman-applet 
exec-once = kdeconnect-indicator 

# exec-once = wal -R &
exec-once = mako 
exec-once = sleep 5 && waybar -c ~/.config/waybar/Hyprland/config.jsonc -s ~/.config/waybar/Hyprland/style.css
exec-once = hyprpaper 
exec-once = systemctl --user start hyprpolkitagent
exec-once = ollama serve 


exec-once = printf "[D-BUS Service]\nName=org.kde.kded6\nExec=/bin/false" > $HOME/.local/share/dbus-1/services/org.kde.kded6.service
exec-shutdown = rm $HOME/.local/share/dbus-1/services/org.kde.kded6.service

source=~/.config/hypr/autostart-per-workspaces/*
