env = QT_QPA_PLATFORM, wayland
env = QT_QPA_PLATFORMTHEME, qt5ct
env = QT_STYLE_OVERRIDE, kvantum
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = MOZ_ENABLE_WAYLAND, 1

exec-once = hyprpm reload -n

monitor=,preferred,auto,1

# Workspaces
$System = 1
$Files = 2
$Chats = 3
$Games = 4
$Virt = 5
$Web = 6
$Dev = 7
$Term = 8
$Misc = 9

source=~/.config/hypr/workspaces/*.conf
source=~/.config/hypr/variables.conf

exec-once = hyprctl reload


input {

    kb_layout = us,ru
    #kb_variant = ,qwerty
    #kb_model = 
    kb_options = grp:alt_shift_toggle, ctrl:nocaps
    #kb_rules =
    numlock_by_default = true

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
        tap-to-click = false
        disable_while_typing = true
    }
}


gestures {
    workspace_swipe_use_r = false
    workspace_swipe_direction_lock = false
    workspace_swipe_forever = false
}

device {
    name = mi-mi-wireless-mouse
    sensitivity = -0.4
}

device {
    name = "yichip-wireless-device-mouse"
    sensitivity = -0.4
}

device {
    name = "instant-usb-optical-mouse"
    sensitivity = -0.4
}

source=~/.config/hypr/plugins/*
source=~/.config/hypr/binds/*
source=~/.config/hypr/misc/*
source=~/.config/hypr/windowrules/*
source=~/.config/hypr/gestures.conf
source=~/.config/hypr/look-and-feel/*
source=~/.config/hypr/autostart.conf
source=~/.config/hypr/autostart-per-workspaces/*

