
preload = ~/.wallpapers/Niko1.png
preload = ~/.wallpapers/Niko2.png
preload = ~/.wallpapers/Niko3.png
preload = ~/.wallpapers/Niko4.png
preload = ~/.wallpapers/Niko5.png
preload = ~/.wallpapers/Niko6.jpg
preload = ~/.wallpapers/Niko7.jpg
preload = ~/.wallpapers/Niko8.jpg
preload = ~/.wallpapers/rw1.png
preload = ~/.wallpapers/rw2.png
preload = ~/.wallpapers/rw3.png
preload = ~/.wallpapers/rw4.png
preload = ~/.wallpapers/rw5.png

wallpaper = ,~/.wallpapers/Niko1.png
