# Bind vars
$mainMod = SUPER 
$modCtrl = $mainMod+CONTROL
$windowResize = $mainMod+SHIFT
$windowMove = $mainMode+ALT

# App vars
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$browser = zen-browser
$menu = wofi --show drun
