bind = $windowResize, V, togglesplit 

bind = $windowResize, F, fullscreen
binde = $windowResize, SPACE, togglefloating

binde = $mainMod, H, layoutmsg, focus l
binde = $mainMod, L, layoutmsg, focus r
binde = $mainMod, K, layoutmsg, focus u
binde = $mainMod, J, layoutmsg, focus d

binde = $windowMove, H, layoutmsg, movewindowto l
binde = $windowMove, L, layoutmsg, movewindowto r
binde = $windowMove, K, layoutmsg, movewindowto u
binde = $windowMove, J, layoutmsg, movewindowto d 

binde = $windowResize, R, layoutmsg, colresize +conf
binde = $windowResize, S, layoutmsg, fit all

binde = $windowResize, H, layoutmsg, colresize -0.1
binde = $windowResize, L, layoutmsg, colresize +0.1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod+SHIFT, TAB, togglegroup
bind = $windowMove, TAB, changegroupactive, f
bind = $windowMove+SHIFT, TAB, changegroupactive, b

